[tool.poetry]
name = "pdf-toolkit-backend"
version = "0.1.0"
description = "PDF Toolkit Backend API"
authors = ["Ashok Mahajan"]

[tool.poetry.dependencies]
python = "^3.9"
flask = "^3.0"
flask-cors = "^5.0"
pdf2docx = "^0.5.6"
opencv-python-headless = "^4.10.0"
pymupdf = "^1.24.0"
python-docx = "^1.1.0"

[tool.poetry.scripts]
app = "api.index:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
