const express = require("express");
const multer = require("multer");
const fs = require("fs-extra");
const Sentry = require("@sentry/node");
const { getBrowser } = require("../utils/browserLauncher");

const router = express.Router();

const storage = multer.memoryStorage();
const upload = multer({
  storage,
  limits: { fileSize: 50 * 1024 * 1024 },
});

router.post("/", upload.single("file"), async (req, res) => {
  let browser;
  try {
    if (!req.file) return res.status(400).json({ error: "File required" });

    const htmlContent = req.file.buffer.toString("utf8");
    console.log("Input HTML length:", htmlContent.length);

    browser = await getBrowser();
    const page = await browser.newPage();
    
    // Set content and wait for it to be parsed
    await page.setContent(htmlContent, { 
      waitUntil: "load", 
      timeout: 30000 
    });

    // Short delay to ensure everything is rendered
    await new Promise(r => setTimeout(r, 500));

    const pdfBuffer = await page.pdf({ 
      format: "A4",
      printBackground: true,
      margin: { top: '20px', right: '20px', bottom: '20px', left: '20px' }
    });

    console.log(`Generated PDF. Size: ${pdfBuffer.length} bytes`);
    
    // Check if it's a valid PDF (just size check)
    if (pdfBuffer.length < 100) {
      throw new Error("Invalid PDF generated by browser engine (file too small).");
    }

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'attachment; filename="converted.pdf"');
    res.send(Buffer.from(pdfBuffer));

  } catch (error) {
    console.error("Conversion Error:", error);
    if (!res.headersSent) {
      res.status(500).json({ error: error.message || "Failed to generate PDF." });
    }
  } finally {
    if (browser) {
      try {
        await browser.close();
      } catch (e) {
        console.error("Error closing browser:", e);
      }
    }
  }
});

module.exports = router;